const articles = [
  {
    name: "first",
    title: "First Article",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas erat imperdiet sed euismod nisi porta. Enim ut tellus elementum sagittis vitae et. Tempus egestas sed sed risus. Pretium lectus quam id leo in. Risus nullam eget felis eget nunc lobortis mattis aliquam. Accumsan in nisl nisi scelerisque eu ultrices. Nam aliquam sem et tortor consequat id. Eget felis eget nunc lobortis mattis. Cursus turpis massa tincidunt dui ut. Mauris ultrices eros in cursus turpis. Tempus egestas sed sed risus pretium quam vulputate dignissim. Tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras.Convallis posuere morbi leo urna molestie at elementum eu facilisis.Mauris nunc congue nisi vitae suscipit tellus mauris. Aliquam sem fringilla ut morbi tincidunt augue interdum velit euismod.Cursus in hac habitasse platea dictumst quisque sagittis purus sit.Sed elementum tempus egestas sed sed risus pretium.Amet commodo nulla facilisi nullam vehicula ipsum a arcu cursus.Scelerisque mauris pellentesque pulvinar pellentesque. Vitae justo eget magna fermentum. Condimentum lacinia quis vel eros. Enim nulla aliquet porttitor lacus luctus accumsan tortor posuere. Purus gravida quis blandit turpis cursus in hac habitasse. Eu facilisis sed odio morbi. Imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Ornare suspendisse sed nisi lacus sed viverra. Turpis in eu mi bibendum neque egestas congue. Nisl rhoncus mattis rhoncus urna neque viverra. Nunc aliquet bibendum enim facilisis gravida neque convallis a cras. Nisi scelerisque eu ultrices vitae.",
  },
  {
    name: "second",
    title: "Second Article",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas erat imperdiet sed euismod nisi porta. Enim ut tellus elementum sagittis vitae et. Tempus egestas sed sed risus. Pretium lectus quam id leo in. Risus nullam eget felis eget nunc lobortis mattis aliquam. Accumsan in nisl nisi scelerisque eu ultrices. Nam aliquam sem et tortor consequat id. Eget felis eget nunc lobortis mattis. Cursus turpis massa tincidunt dui ut. Mauris ultrices eros in cursus turpis. Tempus egestas sed sed risus pretium quam vulputate dignissim. Tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras.Convallis posuere morbi leo urna molestie at elementum eu facilisis.Mauris nunc congue nisi vitae suscipit tellus mauris. Aliquam sem fringilla ut morbi tincidunt augue interdum velit euismod.Cursus in hac habitasse platea dictumst quisque sagittis purus sit.Sed elementum tempus egestas sed sed risus pretium.Amet commodo nulla facilisi nullam vehicula ipsum a arcu cursus.Scelerisque mauris pellentesque pulvinar pellentesque. Vitae justo eget magna fermentum. Condimentum lacinia quis vel eros. Enim nulla aliquet porttitor lacus luctus accumsan tortor posuere. Purus gravida quis blandit turpis cursus in hac habitasse. Eu facilisis sed odio morbi. Imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Ornare suspendisse sed nisi lacus sed viverra. Turpis in eu mi bibendum neque egestas congue. Nisl rhoncus mattis rhoncus urna neque viverra. Nunc aliquet bibendum enim facilisis gravida neque convallis a cras. Nisi scelerisque eu ultrices vitae.",
  },
  {
    name: "third",
    title: "Third Article",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas erat imperdiet sed euismod nisi porta. Enim ut tellus elementum sagittis vitae et. Tempus egestas sed sed risus. Pretium lectus quam id leo in. Risus nullam eget felis eget nunc lobortis mattis aliquam. Accumsan in nisl nisi scelerisque eu ultrices. Nam aliquam sem et tortor consequat id. Eget felis eget nunc lobortis mattis. Cursus turpis massa tincidunt dui ut. Mauris ultrices eros in cursus turpis. Tempus egestas sed sed risus pretium quam vulputate dignissim. Tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras.Convallis posuere morbi leo urna molestie at elementum eu facilisis.Mauris nunc congue nisi vitae suscipit tellus mauris. Aliquam sem fringilla ut morbi tincidunt augue interdum velit euismod.Cursus in hac habitasse platea dictumst quisque sagittis purus sit.Sed elementum tempus egestas sed sed risus pretium.Amet commodo nulla facilisi nullam vehicula ipsum a arcu cursus.Scelerisque mauris pellentesque pulvinar pellentesque. Vitae justo eget magna fermentum. Condimentum lacinia quis vel eros. Enim nulla aliquet porttitor lacus luctus accumsan tortor posuere. Purus gravida quis blandit turpis cursus in hac habitasse. Eu facilisis sed odio morbi. Imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Ornare suspendisse sed nisi lacus sed viverra. Turpis in eu mi bibendum neque egestas congue. Nisl rhoncus mattis rhoncus urna neque viverra. Nunc aliquet bibendum enim facilisis gravida neque convallis a cras. Nisi scelerisque eu ultrices vitae.",
  },
];

export default articles;
